### ISSUE TITLE
[REQUEST] Edit Keyword Action

### ISSUE THREAD

**Issue by bohl3r** [timcrockford/yourls-api-edit-url#4]
I think it would be helpful to add an edit keyword action to the API, so that you may edit a url's keyword after it's been created.

**Comment by timcrockford** [comment]
It's definitely a great addition! I'll try and have a look on the weekend to see what I can do - it shouldn't be that difficult to add something in.

**Comment by timcrockford** [comment]
Better late than never! There's a new commit which adds the change_keyword action to the API, this should give you what you're after.
