### ISSUE TITLE
Install Directory

### ISSUE THREAD

**Issue by ZandarKoad** [timcrockford/yourls-api-edit-url#5]
What is the correct install directory for this plugin?

Most readme.md files in Yourls plugins have a How To section that indicates the correct folder, but not this one.  E.g.:

## How to

- In /user/plugins, create a new folder named FOLDERNAME
- Drop these files in that directory
- Go to the Plugins administration page and activate the plugin
- Have fun

Does it matter what the folder name is?

**Comment by timcrockford** [comment]
Thanks for the feedback! I'll get the readme file updated to clarify this but to answer your question, no, the directory doesn't matter. As long as it's a subdirectory in the plugins folder so YOURLS can find it it should work just fine.
